repos:
  - repo: https://github.com/akaihola/darker
    rev: v3.0.0
    hooks:
    -   id: darker
        args: [--isort]
        additional_dependencies:
            - "black"
            - "isort>5.9"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
