from dateutil.rrule import weekday
from typing import Optional


class weekday:
    def __call__(self, n: Optional[int]) -> weekday: ...
    def __eq__(self, other: weekday) -> bool: ...
    def __init__(self, weekday: int, n: Optional[int] = None) -> None: ...
    def __ne__(self, other: weekday) -> bool: ...
    def __repr__(self) -> str: ...
